services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  db:
    image: mysql:8-debian
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
